### ISSUE TITLE
Is there a way to ignore check for module-info.class in jar

### ISSUE THREAD

**Issue by victorhua** [tehlers/gradle-duplicate-classes-check#2]
With Java 9, module-info.class shows up in jar. 
Here is an example:
      jakarta.ws.rs:jakarta.ws.rs-api:2.1.5, org.apache.logging.log4j:log4j-api:2.10.0

These two jars have no common except for module-info.class.

**Comment by otbe** [comment]
Im also interested in excluding things so I prepared a simple PR that adds a configuration property called `exclusions`. Let me know what you think about it :)

**Comment by tehlers** [comment]
Fixed with #4.
